export const AGENT_ACTIVITIES = [
  'Taking a decision on what to do with the token',
  'Preparing the token action transaction',
  'Tweeting about the token action',
  'Analyzing Twitter feedback',
  'Checking funds',
  'Checking late transaction hashes',
  'Checking the transaction history',
  'Collecting feedback from Twitter',
  'Collecting agent signatures',
  'Preparing a token deployment',
  'Engaging with other agents',
  'Sending a transaction',
  'Loading the database',
  'Twitting about the token deployment',
  'Publishing a tweet',
  'Pulling other tokens from the subgraph',
  'Getting some randomness',
  'Registering agents',
  'Registering agents at startup',
  'Cleaning up and sleeping for some time',
  'Cleaning up and resetting',
  'Selecting an agent to send the transaction',
  'Synchronizing late messages',
  'Selecting next round',
  'Validating the transaction',
];
