# TBA
name: Backend

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js (for package scripts)
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # Configure Yarn network settings for timeout, retries, and reduced concurrency
      - name: Configure Yarn network settings
        run: |
          yarn config set network-timeout 60000         # Set network timeout to 1 minute
          yarn config set network-retries 10             # Retry up to 10 times
          yarn config set network-concurrency 2          # Reduce concurrency to 2 connections

      # Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - uses: snok/install-poetry@v1
        with:
          version: "1.8.5"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true

      # Install backend dependencies
      - run: yarn install:backend

      # Run backend
      # -   run: yarn dev:backend
