name: Binary Tests

on: pull_request

jobs: 
    compile:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4            
            - uses: actions/setup-python@v4
              with:
                python-version: "3.10"
            - uses: snok/install-poetry@v1
              with:
                version: "1.7.1"
                virtualenvs-create: true
                virtualenvs-in-project: false
                virtualenvs-path: ~/my-custom-path
                installer-parallel: true
            - name: Install dependencies
              run: poetry install --no-root
            - name: Permission prebuilt bins for darwin ARM64
              run: | 
                chmod +x bins/darwin/arm64/aea_bin
                chmod +x bins/darwin/arm64/tendermint
            - name: Create Pearl ARM64
              run: pyinstaller pearl_arm64.spec
            - name: Permission the pearl_arm64 binary
              run: chmod +x dist/pearl_arm64
            - name: Test Pearl ARM64 runs
              run: ./dist/pearl_arm64        
    